chat-id: 2
rooms:
    - number: "391"
      members:
        - name: Джавид
          id: id819522445
        - name: Сердар
          id: id818959495
      swap-pending: false
    - number: "392"
      members:
        - name: Таня
          id: id316332619
        - name: Луиза
          id: luliza
      swap-pending: false
    - number: "393"
      members:
        - name: О'Брайен
          id: rooccat
        - name: Максим
          id: maxim.zaytsev2013
      swap-pending: false
    - number: "394"
      members:
        - name: Наиль
          id: paranoiax9
        - name: Дамир
          id: ito_ya
        - name: Данил
          id: khamzd
      swap-pending: false
    - number: "395"
      members:
        - name: Олег
          id: id324195597
        - name: Рамзан
          id: id266736469
        - name: Никита
          id: id171920587
      swap-pending: false
    - number: "396"
      members:
        - name: Настя
          id: nastyfedorova03
        - name: Альбина
          id: a.kariiimova
      swap-pending: false
    - number: "397"
      members:
        - name: Ксения
          id: ksenyf
        - name: Ангелина
          id: angel__ku
      swap-pending: false
    - number: "398"
      members:
        - name: Айта
          id: idnakwonlukimlee
        - name: Руфина
          id: karimovarufina
        - name: Лилия
          id: li.sing
      swap-pending: false
duty-timings:
    - "10:30"
    - "21:30"
clean-timings:
    - "11:00"
    - "18:00"
frequency: 2
current: "397"
clean-day: thursday
clean-hour: "21:00"
retries: 3
retry-interval: 1
dad: 334808440
admins:
    - 334808440
    - 160875598
    - 361384685
